Add Organization RXJS Object
unc-csxl/csxl.unc.edu pull request #105
Opened 2023-10-08 21:12 UTC by jadekeegan

This PR adds and implements the RXJS object for Organization to update our code to be match the preferred method of storing and handling Observables from HTTP requests. This also allows for deletes to be done on the backend without refresh.

## Major Changes
- Added the RX object TS file (copied from the coworking branch).
- Implemented the rx organization object.
- Updated the frontend Organization Admin component/services to use the new RX object.

## Testing
All features were thoroughly tested in the local server by running `honcho start`.

2023-10-14 14:02 UTC, ajaygandecha reviewed
LGTM @jadekeegan -- awaiting final approval from @KrisJordan !

2023-10-14 15:18 UTC, KrisJordan requested changes
Just a few minor items to cleanup and ready to merge!

2023-10-14 15:18 UTC, KrisJordan commented on frontend/src/app/admin/organization/admin-organization.service.ts
> +import { Organization } from "../../..//app/organization/organization.service";
This path feels off, looks like we only need two levels of traversal up (since both this file and the imported are in frontent/src/app/).

2023-10-14 15:18 UTC, KrisJordan commented on frontend/src/app/admin/organization/admin-organization.service.ts
> +import { RxOrganization } from '../../../app/organization/rx-organization';
Same with this import.

2023-10-14 15:18 UTC, KrisJordan commented on frontend/src/app/admin/organization/admin-organization.service.ts
> +             console.log(this.organizations);
We should remove console logs.

2023-10-15 00:01 UTC, KrisJordan approved these changes
LGTM

2023-10-15 00:01 UTC, merged