(Update v. 1.3.0) Add Courses Feature to the CSXL Application
unc-csxl/csxl.unc.edu pull request #222
Opened 2023-12-25 11:34 UTC by ajaygandecha

# Version 1.3.0 - The Academics Tab

This update adds UNC course and section offerings data to the CSXL web application. The web application can now store data on UNC courses, course offerings / sections for each courses, and semesters / terms. The CSXL site now also keeps track of instructors and TAs for courses, as well as locations for lectures and office hours.

All visitors to the CSXL page are able to view a _COMP Course Catalog_ to see all of the courses that the UNC Computer Science department offers, as well as a _Section Offerings_ page where students can view course sections being offered for various terms. Course data is modifiable to the CSXL web page administrator.

This feature adds _5_ new database tables, _25_ new API routes, and _12_ new frontend components to the application. [View the techincal specification document here](https://github.com/unc-csxl/csxl.unc.edu/blob/feature/courses/docs/specs/academics.md).

## New Pages and Features

### Academics Homepage

![Academics Home](https://github.com/unc-csxl/csxl.unc.edu/blob/feature/courses/docs/images/specs/academics/academics-home.png)

The home page for the new Academics feature is available on the side navigation toolbar at `/academics`. The home page contains links to both the _course catalog_ and the _section offerings_ page. In the future, this page will be heavily extended to add personalized academics features for users of the CSXL web app. For now, this page will remain static and exist merely for informational and navigational purposes.

### Course Catalog

![Course catalog](../images/specs/academics/course-catalog.png)

The course catalog page serves as the main hub for students to learn more about COMP courses at UNC. The page exists at the `/academics/catalog` route. The course page shows the courses available in the backend. Right now, the course page shows this data in a simple table. Users can click on courses to see a dropdown to learn more about a course's _credit hours_ and _description_. In the future, when more courses outside of just COMP courses are added here, this page will include a dropdown in the top right that allows users to switch the course subject they look for courses on.

### Section Offerings

![Section offerings](../images/specs/academics/section-offerings.png)

The section offerings page serves as the main hub for students to view offerings of COMP courses by semester / term. The page exists at the `/academics/offerings` route. The section page shows this data in a table. Users can click on courses to see a dropdown to learn more about a course. There is also a dropdown in the top right that allows users to view course offerings based on all of the semesters / terms saved in the database. In the future, when more courses outside of just COMP courses are added here, this page will include another dropdown in the top right that allows users to switch the course subject they look for courses on.

### Admin Pages

This update also adds numerous course editing admin pages that allow the administrator of the site to update course, section, term, and room data. View more details in the technical specification document linked at the top section.

## Next Steps to Release
- [ ] Create Migration Scripts (@KrisJordan)
- [ ] Consider Hiding Instructor Column For Now (need approval from @KrisJordan - but the rationale is that we still need to get Professors to have a CSXL login for us to do this effectively.

## Future Considerations
- Add more courses other than COMP-coded courses to the site and implement filtering on the Course Catalog and Section Offerings pages for this.
- Enable adding Lecturers and TAs to course sections.
- Enable adding students to courses and implement an administrative view for this.

2023-12-27 05:15 UTC, KrisJordan requested changes
WOW this is quite the PR! Amazing work getting these foundational entities and APIs in place. So many features are going to be built depending on this structure.

Couple of things to look into before merge:

1. Getting the old "ExpressionChangedAfterItHasBeenCheckedError" warning in the academics pages. Perhaps the gear icon?
2. Seeing 2 failing tests on my end in `section_test`: `test_create_as_root` and `test_update_as_root`.

Couple of items to put on a backburner:

1. Marking courses as inactive or deprecated and no longer showing them in the course catalog (though old sections should show in the appropriate semesters).

There are some comments throughout, none seem super high order, but a few might be worth tackling now others added as issues.

Something we should discuss in the Fall is whether we should consolidate editors for admins in-situ on the public frontend (events/orgs does this) vs. have an admin listing page for it. This would apply to sections/courses. The gear / admin area would still need to exist for rooms / terms. Nothing to do on this front now, what you have is great, but wondering if it ultimately avoids some duplication of listings (and since we're bundling all admin features in the user feature module on the front-end anyway...)

Pushing up a commit of a few tidying changes mentioned in the commit.

Really great work here!!!! 🚀

2023-12-27 05:15 UTC, KrisJordan commented on frontend/src/app/academics/academics-home/academics-home.component.html
I wonder if the home page for academics should be to list sections in the current semester and then link off to the course catalog in some way? Seems like current/next semester offerings are likely the most commonly accessed items (at least until we get office hours locations, office hours queues, and students as members of courses going).

2023-12-27 05:15 UTC, KrisJordan commented on frontend/src/app/academics/academics-home/academics-home.component.ts
> +    this.gearService.showAdminGear('academics.*', '*', '', 'academics/admin/');
Going to update this to take directly to sections.

2023-12-28 20:54 UTC, ajaygandecha commented on backend/models/roster_role.py
> +    INSTRUCTOR = 3
Yes, this worked!

2023-12-28 20:57 UTC, ajaygandecha commented on backend/services/academics/term.py
> +        query = select(TermEntity).where(TermEntity.start < date, date < TermEntity.end)
Fixed!

2023-12-28 21:06 UTC, ajaygandecha commented on frontend/src/app/academics/academics-admin/room/admin-room.component.html
> +      </td>
Sounds good to me

2023-12-28 21:07 UTC, ajaygandecha commented on backend/entities/academics/section_entity.py
> +        ]
@KrisJordan hmm, not entirely sure how to build this into the SQL. Thoughts on how this might be implemented?

2023-12-28 21:18 UTC, ajaygandecha commented on frontend/src/app/academics/academics-home/academics-home.component.html
@KrisJordan, do you want `/academics` to be replaced to the section offerings view then, or do you want the academics tab to redirect to `academics/offerings`? I thought about doing this too but left the academics home page here because I was thinking that many ex or final projects might use it.

2023-12-28 21:20 UTC, ajaygandecha commented
@KrisJordan, all but two comments resolved! 

- All tests pass now, however there are two warnings on a `get` test I have been trying to resolve for quite a while now and have had no luck. Was hoping maybe you could take a look here.
- Wrote a comment on the review pt about storing staff, however I am a bit unsure on what you prefer here! 😃
- Lastly, wrote one comment about the Academics Home - let me know what you were thinking!

2023-12-28 21:22 UTC, ajaygandecha commented on frontend/src/app/academics/academics-admin/room/admin-room.component.html
> +      </td>
@KrisJordan, I had to put it on the text. Putting the action on the row means that the action runs also when the delete button is pressed!

2023-12-29 03:05 UTC, KrisJordan approved these changes
I'm about to push and PR a few minor suggestions for this branch.

2023-12-29 03:05 UTC, KrisJordan commented on backend/entities/academics/section_entity.py
> +        ]
Yep, will push and PR separately.

2023-12-29 05:20 UTC, KrisJordan commented on frontend/src/app/academics/academics-home/academics-home.component.html
We can launch as is and maybe think about design iteration (such as adding the section listing widget beneath the welcome to academics message and maybe only show the current semester)

2023-12-30 14:08 UTC, KrisJordan commented
Added the migration script and some documentation on how to move through the process of generating a migration script in the future.

In the process, I identified two issues that will need resolution, ideally before deploy:

1. The section editor front-end does not seem to function without any existing sections (step to try: checkout `main`, delete database, create database, reset demo, run `alembic stamp 63fc`, checkout `feature/courses`, run `alembic upgrade head`, create a term, create a course, then try to create a section)
2. Our explosion of COMP590 offerings means we likely need a Section entity title override and description override field a la https://crypto.unc.edu/UNC_classes/spring2024/

2023-12-30 14:31 UTC, KrisJordan commented
Additionally, I've fixed the test warnings, but it's led to an error in deleting a section in the test `test_delete_as_root`.

This is a cascading delete issue. I'm adding a delete cascade to the `SectionEntity` which resolves the failing test. Push coming after this comment.

2023-12-31 01:50 UTC, merged