Feedback Form Feature
unc-csxl/csxl.unc.edu pull request #256
Opened 2024-02-06 21:04 UTC by tmattvu

Draft pr to keep track of updates!

2024-02-11 02:06 UTC, ajaygandecha requested changes
Sorry for the late reply to this @tmattvu! This is looking great, nice work! Left a few comments regarding some of the models, let me know what you think.

2024-02-11 02:06 UTC, ajaygandecha commented on backend/entities/feedback_entity.py
> +    user = relationship("UserEntity")
Will we need a back-populating field here, such as if students need to see the feedback they have submitted? Regardless, does not seem to be a major concern for now.

2024-02-11 02:06 UTC, ajaygandecha commented on backend/entities/feedback_entity.py
> +    has_resolved: Mapped[bool] = mapped_column(Boolean)
Nit: I think Kris has moved us to a convention where flag fields do not include an `is_` or a `has_` prefix! `resolved` works perfectly here as the field name.

2024-02-11 02:06 UTC, ajaygandecha commented on backend/entities/feedback_entity.py
> +    def from_draft_model(cls, model: Feedback) -> Self:
Might be wrong, but I think this method might be redundant due to `from_model` below it! I think these two methods are duplicates, based on their parameters and output.

2024-02-11 02:06 UTC, ajaygandecha commented on backend/entities/feedback_entity.py
> +    def to_model(self, subject: User | None = None) -> Feedback:
`subject` might not be needed as an input here!

2024-02-11 02:06 UTC, ajaygandecha commented on backend/entities/feedback_entity.py
> +    def to_details_model(self, subject: User | None = None) -> FeedbackDetails:
subject might not be needed as an input here!

2024-02-11 02:06 UTC, ajaygandecha commented on backend/models/feedback_details.py
> +class FeedbackDetails(Feedback):
Since there are no back-populating relationship fields, is this model necessary?

2024-02-11 02:06 UTC, ajaygandecha commented on backend/models/feedback.py
> +class FeedbackForm(BaseModel):
This model might not be necessary, since it looks equivalent to `Feedback`!

2024-02-11 16:01 UTC, KrisJordan commented
For frontend purposes, let's get Feedback into its own module, separate from the main module, so that it's not loaded with every page load.

2024-04-27 23:13 UTC, ajaygandecha commented
Any updates @tmattvu ?

2024-04-27 23:40 UTC, tmattvu commented
> Any updates @tmattvu ?

No sir, but I just finished group reservations :)

2024-04-27 23:48 UTC, ajaygandecha commented
Closing branch!

2024-04-27 23:48 UTC, closed without merging