357 avoid duplication of polling data in coworking home
unc-csxl/csxl.unc.edu pull request #373
Opened 2024-03-28 00:44 UTC by JohnSchachte

closes #357 

All polling will now take place with the RxObject 'RxCoworkingStatus' to avoid duplicate pulling. 
I also went outside the scope of this branch to refactor how the Room Reservation Service was being utilized and removed duplicate Reservation State Change Methods (like cancel Reservation etc) from this child class.

Let me know if there are additional items that should be cleaned up!

Note:
THe original issue: https://github.com/unc-csxl/csxl.unc.edu/issues/357 mentions 'f there is something missing from the status API endpoint, such as the bound of future reservations is too short (worth checking) then we can fix that.'. I was not sure what this was referring to or how to test if this was an issue. Let me know if this is still worth looking into! Thank you.

2024-04-08 18:17 UTC, JohnSchachte commented
Upated the upcoming reservations to be rendering asynchronously with a property in Coworking Home Component class instead of a method call per Kris. Pulled Main and merged with this branch so there should be no conflicts at this time.

2024-04-15 19:58 UTC, KrisJordan requested changes
Almost there; one more refactoring away from piping async over a method call and I think this is done. Glad to see us down to a single network request, this is just an optimization for client-side efficiency purposes.

2024-04-15 19:58 UTC, KrisJordan commented on frontend/src/app/coworking/coworking-home/coworking-home.component.html
> +          <ng-container *ngFor="let r of initUpcomingReservations() | async">
We should see if we can drop this method call, as well. This is looking really close!

2024-04-27 23:22 UTC, ajaygandecha reviewed
LGTM, I am going to re-request Kris for a review here.

2024-04-27 23:22 UTC, ajaygandecha commented on frontend/src/app/coworking/reservation/reservation.service.ts
> +    let payload = { id: reservation.id, state: 'CHECKED_IN' };
Nit: Would be good to use an `enum` rather than the string literal `'CHECKED_IN'`. This might be out of scope for this branch though

2024-05-16 08:55 UTC, KrisJordan reviewed
Looking good! I'm having trouble successfully testing on my iPad, so I may need @ajaygandecha to confirm coworking is still functional (drop in and room reservation) from the front-end. Then we can get this merged.

I'm taking a stab at cleaning up one section of code where there was  use  of double not operator to coalesce undefined/null to boolean.

2024-05-18 20:26 UTC, ajaygandecha approved these changes
@KrisJordan looks like it is working on my end!

2024-05-20 21:11 UTC, KrisJordan reviewed
LGTM

2024-05-20 21:12 UTC, KrisJordan approved these changes

2024-05-20 21:15 UTC, merged