Task/CSXL-597: Recurring Office Hours Events
unc-csxl/csxl.unc.edu pull request #652
Opened 2024-12-03 14:42 UTC by jadekeegan

This PR adds functionality for recurring OH events on the backend and frontend. Specifically, it allows for the creation and deletion of recurring events.

## Testing
1. Click on the button to create a new event for a course site.
2. Set the recurring events option to "weekly".
3. Select which days of the week the event should recur on.
4. Select an end date for the recurrence.
5. Ensure that all expected events are created (either in the current/future section).

## Future Development
- When deleting a recurring event, create a UI to show the next few events in the pattern that will be deleted.
- Add update functionality for recurring events.
- Restrict end date to end of term / two weeks after EOT.

> _This PR resolves #597._

2024-12-03 18:09 UTC, ajaygandecha requested changes
Great start @jadekeegan, amazing to see this come together! 🥳 

Added review comments for the backend. I am unable to test this functionality on the frontend despite resetting the database, trying to log in as Ina or Root, creating a new course site. This might be due to errors with the test data! When clicking "Create Event", I get the following error:

```
TypeError: undefined is not an object (evaluating 'this.myCoursesService.currentTerms()[0].end') — 
```
This happens even when trying to edit the term's end time to be past today. I can review the frontend once this gets fixed!

2024-12-03 18:09 UTC, ajaygandecha commented on frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.ts
> +    Mon: false,
Making DoWs as an enum might help to prevent future issues using strings as keys.

2024-12-03 18:09 UTC, ajaygandecha commented on frontend/src/app/my-courses/course/office-hours/office-hours.resolver.ts
> +      recurrence_id: -1
Should this be `null` instead?

2024-12-03 18:09 UTC, ajaygandecha commented on backend/test/services/office_hours/office_hours_recurrence_test.py
Looking great! We are at 93% coverage with missing coverage for thrown `RecurringOfficeHourEventException`s on lines `124` and `141` of `backend/services/office_hours/office_hours_recurrence.py`.

2024-12-03 18:09 UTC, ajaygandecha commented on backend/entities/office_hours/office_hours_recurrence_entity.py
> +class OfficeHoursRecurrenceEntity(EntityBase):
(This also means a recommendation to rename entities and models from `OfficeHoursRecurrence` --> `OfficeHoursRecurrencePattern`!)

2024-12-03 19:10 UTC, jadekeegan commented on backend/services/office_hours/office_hours_recurrence.py
> +        # error out if recurrence end date is before 1st OH event
Handled in the exception at the end!

2024-12-04 17:44 UTC, ajaygandecha approved these changes
Code LGTM, will bubble this up to @KrisJordan for the final approval!

2024-12-31 05:58 UTC, KrisJordan commented
LGTM as well, will add the migration and get deployed for Spring. Great work @jadekeegan !

2024-12-31 06:15 UTC, KrisJordan commented
@jadekeegan after code review I went to validate via click through and ran into a few minor concerns. Some of these can be punted on, but I think the first might be a blocker.

1. When attempting to save a recurring event, I'm currently getting an error that Python can't compare offset-naive and offset-aware datetimes here: https://github.com/unc-csxl/csxl.unc.edu/blob/task/CSXL-597/backend/services/office_hours/office_hours_recurrence.py#L99

Perhaps this is a Chrome widgets issue? The date is selected by a date selector and time through the date + time picker. Based on network tab, this appears to be the case:

<img width="424" alt="Screenshot 2024-12-30 at 10 12 28 PM" src="https://github.com/user-attachments/assets/a4a79bec-27fe-4fd8-a488-4aa55b2cfd5f" />

2. When selecting recurring days, the checkbox makes dates scroll out of view: 
<img width="625" alt="Screenshot 2024-12-30 at 10 14 35 PM" src="https://github.com/user-attachments/assets/960a15bc-36f5-4e95-849d-0f4a4c5033af" />

Perhaps we drop the check and just use shading to indicate?

3. Edge case: If you attempt to create a new event for a course after the semester has ended, you get a blank screen with no error message. Some kind of error message is probably appropriate here.

2024-12-31 06:49 UTC, KrisJordan commented
I believe I've fixed the checkbox issue, but actually made a regression on the JavaScript time issue. Will revisit in the morning; at present (with West Coast local offset) I seem to be compounding a timezone offset issue between front end and backend.

Migration ready to go otherwise.

2025-01-15 01:27 UTC, ajaygandecha commented
Wait @KrisJordan / @jadekeegan, curious of the status on this PR!

2025-01-17 19:44 UTC, ajaygandecha commented
@KrisJordan and @jadekeegan, did another test of this feature on both Safari and Chrome for various different patterns and edge cases -- I am not getting any errors, things seem to be working.

I caught only one missing edge case - the frontend errored out in the case where the recurrence end date was after the first event's start time, but due to the pattern, no events could be created before the end date.

For example: 
- Today is Fri
- Attempt to create a recurrent event with pattern M Tu, but the recurrent end date is Sun
- This returned an empty of list events `[]` rather than erroring out, so I added a check in the backend to account for this.

Other than this, this still looks good to me. @KrisJordan, anything else you found that needs fixing?

2025-01-22 01:21 UTC, merged