Add form validation
unc-csxl/csxl.unc.edu pull request #91
Opened 2023-09-22 08:13 UTC by atoneyd

This PR adds more entry validation to the organization editor/creation form.

# Major Changes
- Added character limit of 150 to short description
- Added character limit of 2000 to long description
- Added valid email check
- Enforcing slugs to be limited to lowercase letters, numbers, and dashes
- Org Details page will default to short description if no long description is provided

# Testing
- Run `honcho start`
- Log in as Admin
- Navigate to organization editor
- Test new validations

# Developer notes
Ticket requested validation for links; not something we can really do with just regex since almost anything can be a link. Did not modify anything for now but I'm open to discussion if we still want to implement this.

Closes #64

2023-09-22 14:02 UTC, briannata requested changes
LGTM, but just a few nits!

Note: we should discuss whether we want to continue using links for images or change to an image upload

2023-09-22 14:04 UTC, atoneyd commented on frontend/src/app/organization/organization-editor/organization-editor.component.html
> +                <input matInput placeholder="" formControlName="slug" name="slug">
I added validators in the TS file which already make it required

2023-09-22 14:21 UTC, briannata approved these changes
LGTM!

2023-09-22 14:36 UTC, briannata requested changes
Can you add it so that the organization details page uses the short description if the long description doesn't exist (since a long description isn't required in the creation form).

2023-09-29 13:49 UTC, briannata approved these changes
LGTM!

2023-10-03 13:09 UTC, merged